"""デフォルトテンプレート.

各関数はプロジェクト名等を受け取り、ファイル内容の文字列を返す.
"""


def package_init(name: str, version: str) -> str:
    """パッケージ __init__.py."""
    return f'''"""{name}パッケージ."""

__version__ = "{version}"
'''


def main_py(name: str) -> str:
    """main.py エントリーポイント."""
    return f'''"""CLIエントリーポイント."""

import click

from {name} import __version__
from {name}.commands.hello import hello


@click.group(invoke_without_command=True)
@click.version_option(version=__version__)
@click.pass_context
def cli(ctx: click.Context) -> None:
    """{name} CLI."""
    if ctx.invoked_subcommand is None:
        click.echo(f"{name} v{{__version__}}")
        click.echo("A CLI application generated by Pochisanpo.")
        click.echo("")
        click.echo("Commands:")
        click.echo("  hello   Say hello")
        click.echo("")
        click.echo(f"Run '{name} <command> --help' for more info.")


cli.add_command(hello)


def main() -> None:
    """エントリーポイント."""
    cli()


if __name__ == "__main__":
    main()
'''


def commands_init() -> str:
    """commands/__init__.py."""
    return '''"""コマンドパッケージ.

コマンド層の責務:
- CLIオプション/引数の定義（@click.option, @click.argument）
- 対話フローの制御（prompts/を使用）
- core/のロジックを呼び出す
- 結果を出力する（click.echo）
"""
'''


def hello_py(name: str) -> str:
    """commands/hello.py サンプルコマンド."""
    return f'''"""helloコマンド.

コマンド層の責務:
- CLIオプション/引数の定義（@click.option, @click.argument）
- 対話フローの制御（prompts/を使用）
- core/のロジックを呼び出す
- 結果を出力する（click.echo）

対話型にする例:
    from {name}.prompts import ask_name
    name = ask_name()  # ユーザーに入力を求める

ロジック呼び出し例:
    from {name}.core.greeter import create_greeting
    message = create_greeting(name)
"""

import click

from {name}.core.greeter import create_greeting


@click.command()
@click.option("--name", default="World", help="Name to greet.")
def hello(name: str) -> None:
    """挨拶を表示する."""
    message = create_greeting(name)
    click.echo(message)
'''


def core_init() -> str:
    """core/__init__.py."""
    return '''"""コアロジックパッケージ.

コア層の責務:
- ビジネスロジック（CLIに依存しない純粋な処理）
- テストしやすい関数/クラス
- 外部ライブラリとの連携

commands/から呼び出される.
prompts/やclick等のCLI関連をimportしない.
"""
'''


def greeter_py() -> str:
    """core/greeter.py サンプルロジック."""
    return '''"""挨拶ロジック.

コア層の責務:
- ビジネスロジック（CLIに依存しない純粋な処理）
- テストしやすい関数/クラス
- 外部ライブラリとの連携

commands/から呼び出される.
prompts/やclick等のCLI関連をimportしない.
"""


def create_greeting(name: str) -> str:
    """挨拶メッセージを生成する.

    Args:
        name: 挨拶する名前.

    Returns:
        挨拶メッセージ.
    """
    return f"Hello, {name}!"
'''


def prompts_init(name: str) -> str:
    """prompts/__init__.py."""
    return f'''"""対話型入力の定義.

prompts層の責務:
- click.prompt(), click.confirm() を使った質問関数
- questionary を使ったリッチな選択UI（オプション）
- 入力バリデーション

commands/から呼び出される.

使用例:
    from {name}.prompts import ask_name, confirm_proceed
    name = ask_name()
    if confirm_proceed():
        ...
"""

import click


def ask_name(default: str = "World") -> str:
    """名前を対話的に取得する."""
    return click.prompt("Name", default=default)


def confirm_proceed() -> bool:
    """続行するか確認する."""
    return click.confirm("Proceed?", default=True)
'''


def utils_init(name: str) -> str:
    """utils/__init__.py."""
    return f'''"""ユーティリティ関数.

utils層の責務:
- 汎用的なヘルパー関数
- ファイル操作、パス処理
- 設定ファイルの読み書き

どの層からも呼び出し可能.

使用例:
    from {name}.utils import some_helper
"""
'''


def exceptions_py(name: str) -> str:
    """exceptions.py カスタム例外."""
    class_name = name.title().replace("_", "").replace("-", "")
    return f'''"""カスタム例外.

アプリ固有の例外を定義する.

使用例:
    from {name}.exceptions import {class_name}Error

    raise {class_name}Error("Something went wrong")
"""


class {class_name}Error(Exception):
    """{name}の基底例外."""

    pass
'''


def tests_init(name: str) -> str:
    """tests/__init__.py."""
    return f'''"""{name}のテストパッケージ."""
'''


def test_cli_py(name: str) -> str:
    """tests/test_cli.py."""
    return f'''"""CLIテスト."""

from click.testing import CliRunner

from {name}.main import cli


def test_welcome() -> None:
    """引数なし実行時のウェルカム表示テスト."""
    runner = CliRunner()
    result = runner.invoke(cli, [])
    assert result.exit_code == 0
    assert "{name}" in result.output
    assert "Pochisanpo" in result.output


def test_hello() -> None:
    """helloコマンドのテスト."""
    runner = CliRunner()
    result = runner.invoke(cli, ["hello"])
    assert result.exit_code == 0
    assert "Hello, World!" in result.output


def test_hello_with_name() -> None:
    """helloコマンドのnameオプションテスト."""
    runner = CliRunner()
    result = runner.invoke(cli, ["hello", "--name", "Pochi"])
    assert result.exit_code == 0
    assert "Hello, Pochi!" in result.output
'''


def pyproject_toml(name: str, version: str) -> str:
    """pyproject.toml."""
    return f"""[project]
name = "{name}"
version = "{version}"
description = "A CLI application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.0.0",
]

[project.scripts]
{name} = "{name}.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/{name}"]
"""


def readme_md(name: str) -> str:
    """README.md."""
    return f"""# {name}

A CLI application generated by Pochisanpo.

## Installation

```bash
uv sync
```

## Usage

```bash
uv run {name}              # Show welcome message
uv run {name} hello        # Say hello
uv run {name} hello --name Pochi
```

## Project Structure

```
src/{name}/
├── commands/     # CLI commands (thin layer)
├── core/         # Business logic
├── prompts/      # Interactive prompts
├── utils/        # Utilities
└── exceptions.py # Custom exceptions
```
"""
