"""initコマンド - 新規CLIプロジェクトを生成."""

from pathlib import Path

import click

from pochisanpo import __version__


@click.command()
@click.argument("name")
def init(name: str) -> None:
    """新規CLIプロジェクトを生成する.

    NAMEはプロジェクト名.
    """
    project_dir = Path(name)

    if project_dir.exists():
        click.echo(f"Error: '{name}' already exists.", err=True)
        raise SystemExit(1)

    # ディレクトリ構成を作成
    src_dir = project_dir / "src" / name
    commands_dir = src_dir / "commands"
    tests_dir = project_dir / "tests"

    commands_dir.mkdir(parents=True)
    tests_dir.mkdir(parents=True)

    # __init__.py を作成
    (src_dir / "__init__.py").write_text(
        f'''"""{name}パッケージ."""

__version__ = "{__version__}"
''',
        encoding="utf-8",
    )

    # commands/__init__.py を作成
    (commands_dir / "__init__.py").write_text(
        '''"""コマンドパッケージ."""
''',
        encoding="utf-8",
    )

    # commands/hello.py を作成
    (commands_dir / "hello.py").write_text(
        '''"""helloコマンド."""

import click


@click.command()
@click.option("--name", default="World", help="Name to greet.")
def hello(name: str) -> None:
    """挨拶を表示する."""
    click.echo(f"Hello, {name}!")
''',
        encoding="utf-8",
    )

    # main.py を作成
    (src_dir / "main.py").write_text(
        f'''"""CLIエントリーポイント."""

import click

from {name} import __version__
from {name}.commands.hello import hello


@click.group()
@click.version_option(version=__version__)
def cli() -> None:
    """{name} CLI."""
    pass


cli.add_command(hello)


def main() -> None:
    """エントリーポイント."""
    cli()


if __name__ == "__main__":
    main()
''',
        encoding="utf-8",
    )

    # tests/__init__.py を作成
    (tests_dir / "__init__.py").write_text(
        f'''"""{name}のテストパッケージ."""
''',
        encoding="utf-8",
    )

    # tests/test_cli.py を作成
    (tests_dir / "test_cli.py").write_text(
        f'''"""CLIテスト."""

from click.testing import CliRunner

from {name}.main import cli


def test_hello() -> None:
    """helloコマンドのテスト."""
    runner = CliRunner()
    result = runner.invoke(cli, ["hello"])
    assert result.exit_code == 0
    assert "Hello, World!" in result.output


def test_hello_with_name() -> None:
    """helloコマンドのnameオプションテスト."""
    runner = CliRunner()
    result = runner.invoke(cli, ["hello", "--name", "Pochi"])
    assert result.exit_code == 0
    assert "Hello, Pochi!" in result.output
''',
        encoding="utf-8",
    )

    # pyproject.toml を作成
    (project_dir / "pyproject.toml").write_text(
        f"""[project]
name = "{name}"
version = "{__version__}"
description = "A CLI application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.0.0",
]

[project.scripts]
{name} = "{name}.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/{name}"]
""",
        encoding="utf-8",
    )

    # README.md を作成
    (project_dir / "README.md").write_text(
        f"""# {name}

A CLI application generated by Pochisanpo.

## Installation

```bash
uv sync
```

## Usage

```bash
uv run {name} hello
uv run {name} hello --name Pochi
```
""",
        encoding="utf-8",
    )

    click.echo(f"Created project '{name}'")
    click.echo(f"  cd {name}")
    click.echo("  uv sync")
    click.echo(f"  uv run {name} hello")
